package com.mt.access.domain.model.audit;
public class AuditActionName {
    public static final String DELETE_TENANT_CLIENT = "DELETE_TENANT_CLIENT";
    public static final String CREATE_TENANT_CLIENT = "CREATE_TENANT_CLIENT";
    public static final String UPDATE_TENANT_CLIENT = "UPDATE_TENANT_CLIENT";
    public static final String CREATE_TENANT_CORS_PROFILE = "CREATE_TENANT_CORS_PROFILE";
    public static final String UPDATE_TENANT_CORS_PROFILE = "UPDATE_TENANT_CORS_PROFILE";
    public static final String DELETE_TENANT_CORS_PROFILE = "DELETE_TENANT_CORS_PROFILE";
    public static final String CREATE_TENANT_CACHE_PROFILE = "CREATE_TENANT_CACHE_PROFILE";
    public static final String UPDATE_TENANT_CACHE_PROFILE = "UPDATE_TENANT_CACHE_PROFILE";
    public static final String DELETE_TENANT_CACHE_PROFILE = "DELETE_TENANT_CACHE_PROFILE";
    public static final String CREATE_TENANT_ENDPOINT = "CREATE_TENANT_ENDPOINT";
    public static final String UPDATE_TENANT_ENDPOINT = "UPDATE_TENANT_ENDPOINT";
    public static final String DELETE_TENANT_ENDPOINT = "DELETE_TENANT_ENDPOINT";
    public static final String DELETE_TENANT_PERMISSION = "DELETE_TENANT_PERMISSION";
    public static final String CREATE_TENANT_PERMISSION = "CREATE_TENANT_PERMISSION";
    public static final String UPDATE_TENANT_PERMISSION = "UPDATE_TENANT_PERMISSION";
    public static final String CREATE_TENANT_PROJECT = "CREATE_TENANT_PROJECT";
    public static final String CREATE_SUB_REQUEST = "CREATE_SUB_REQUEST";
    public static final String APPROVE_SUB_REQUEST = "APPROVE_SUB_REQUEST";
    public static final String CANCEL_SUB_REQUEST = "CANCEL_SUB_REQUEST";
    public static final String REJECT_SUB_REQUEST = "REJECT_SUB_REQUEST";
    public static final String CREATE_TENANT_ROLE = "CREATE_TENANT_ROLE";
    public static final String UPDATE_TENANT_ROLE = "UPDATE_TENANT_ROLE";
    public static final String DELETE_TENANT_ROLE = "DELETE_TENANT_ROLE";
    public static final String MGMT_LOCK_USER = "MGMT_LOCK_USER";
    public static final String USER_UPDATE_PWD = "USER_UPDATE_PWD";
    public static final String USER_FORGET_PWD = "USER_FORGET_PWD";
    public static final String USER_RESET_PWD = "USER_RESET_PWD";
    public static final String USER_UPDATE_PROFILE = "USER_UPDATE_PROFILE";
    public static final String ADD_TENANT_ADMIN = "ADD_TENANT_ADMIN";
    public static final String DELETE_TENANT_ADMIN = "DELETE_TENANT_ADMIN";
}
